# Generated by Django 3.1.5 on 2021-02-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria_frontend.order'),
        ),
    ]
